# Windows Build Configuration for AppVeyor
# http://www.appveyor.com/docs/appveyor-yml

# version format
version: "{build}"

os:
  - Visual Studio 2017
  - Visual Studio 2015

platform:
  - x64

configuration:
  - Debug
  - Release

branches:
  only:
    - master

matrix:
  fast_finish: true
  exclude:
    - os: Visual Studio 2015
      configuration: Debug

# scripts that run after cloning repository
install:
  - git clone --depth=1 https://github.com/google/googletest.git      third_party/googletest
  - git clone --depth=1 https://github.com/google/re2.git             third_party/re2
  - set PATH=c:\Python36;%PATH%

before_build:
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" (call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64)
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" (call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64)

build:
  parallel: true  # enable MSBuild parallel builds
  verbosity: minimal

build_script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=install -DRE2_BUILD_TESTING=OFF
  - cmake --build . --target install --config %CONFIGURATION%

test_script:
  - ctest -C %CONFIGURATION% --output-on-failure

notifications:
  - provider: Email
    to:
      - dneto@google.com
    subject: 'Effcee Windows Build #{{buildVersion}}: {{status}}'
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
