module(name = "effcee", version = "1.2026.0")
"""
Effcee is a C++ library for stateful pattern matching of strings inspired by
LLVM's FileCheck.
"""

bazel_dep(name = "rules_python", version = "2.2.0")
python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(python_version = "3.12")

bazel_dep(
    name = "googletest",
    version = "1.17.0",
    dev_dependency = True,
)

bazel_dep(name = "re2", version = "2025-11-05.bcr.1")
# re2 2025-11-05.bcr.1 depends on abseil_cp 20250814.1 which is d38452e1ee03523a208362186fd42248ff2609f6
